ProjectCBAG/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from ProjectCBAG import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('authorization.urls')),
    path('groups/', include('academic_groups.urls')),
]

academic_groups/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('academic_groups/<int:pk>', views.AcademicGroupDetailView.as_view(), name='academicgroup_detail'),
    path('students/new', views.StudentCreateView.as_view(), name='student_create'),
    path('students/<int:pk>/delete', views.StudentDeleteView.as_view(), name='student_delete'),
    path('students/<int:pk>', views.StudentDetailView.as_view(), name='student_detail'),
    path('exams/', views.AcademicGroupExamListView.as_view(), name='exam_list'),
    path('exams/new', views.AcademicGroupExamCreateView.as_view(), name='exam_create'),
    path('exams/<int:pk>/delete', views.AcademicGroupExamDeleteView.as_view(), name='exam_delete'),
    url(r'^student/(?P<student_id>[0-9]+)/edit_student_exams/$', views.edit_student_exams, name='edit_student_exams'),
    url(r'^events/$', views.events, name='events'),
    url(r'^add_event/$', views.add_event, name='add_event'),
    url(r'^event/add_student/$', views.event_add_student, name='event_add_student'),
    url(r'^edit_event_group/$', views.edit_event_group, name='edit_event_group'),
    url(r'^delete_event_group/$', views.delete_event_group, name='delete_event_group'),
    url(r'^jury/$', views.jury, name='jury'),
]

authorization/urls.py
from django.urls import path

from authorization import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

academic_groups/models.py
import djchoices
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Avg


def validate_telephone_number(telephone_number):
    if telephone_number[0] != '+':
        return ValidationError(
            '%(telephone_number) is not a telephone number',
            params={'telephone_number': telephone_number},
        )


class Exam(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')

    class Meta:
        verbose_name = 'Экзамен'
        verbose_name_plural = 'Экзамены'

    def __str__(self):
        return self.name


class AcademicGroup(models.Model):
    institute = models.CharField(max_length=200, verbose_name='Институт')
    course = models.PositiveSmallIntegerField(default=1, verbose_name='Курс')
    name = models.CharField(max_length=6, verbose_name='Название')
    starosta = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Староста')
    starosta_phone_number = models.CharField(max_length=12, validators=[validate_telephone_number],
                                             verbose_name='Номер старосты')
    # exams = models.ManyToManyField(Exam, blank=True, verbose_name='Экзамены')
    curator = models.CharField(max_length=50, verbose_name='Куратор')

    class Meta:
        verbose_name = 'Академическая группа'
        verbose_name_plural = 'Академические группы'

    def __str__(self):
        return self.name


class AcademicGroupExam(models.Model):
    academic_group = models.ForeignKey(AcademicGroup, on_delete=models.CASCADE, verbose_name='Академическая группа')
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, verbose_name='Экзамен')

    class Meta:
        verbose_name = 'Экзамен академической группы'
        verbose_name_plural = 'Экзамены академичских групп'
        unique_together = ('academic_group', 'exam')

    def __str__(self):
        return f'{self.academic_group.name} - {self.exam.name}'


class EducationalFormChoices(djchoices.DjangoChoices):
    budget = djchoices.ChoiceItem(0, 'Бюджет')
    contract = djchoices.ChoiceItem(1, 'Контракт')


class Student(models.Model):
    name = models.CharField(max_length=50, verbose_name='ФИО')
    educational_form = models.PositiveSmallIntegerField(choices=EducationalFormChoices.choices,
                                                        verbose_name='Форма обучения')
    academic_group = models.ForeignKey(AcademicGroup, on_delete=models.CASCADE, verbose_name='Академическая группа')

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

    @property
    def average_score(self):
        average_score = self.examresult_set.aggregate(average_score=Avg('score'))['average_score']
        if average_score is not None:
            return average_score
        else:
            return 0.0

    def __str__(self):
        return self.name


class ExamResult(models.Model):
    score = models.PositiveSmallIntegerField(default=0, verbose_name='Баллы')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='Студент')
    academic_group_exam = models.ForeignKey(AcademicGroupExam, on_delete=models.CASCADE,
                                            verbose_name='Экзамен академической группы')

    class Meta:
        verbose_name = 'Результат экзамена'
        verbose_name_plural = 'Результаты экзаменов'

    def __str__(self):
        return str(self.score)


class EventAreaChoices(djchoices.DjangoChoices):
    scientific = djchoices.ChoiceItem(0, 'Научная')
    cultural = djchoices.ChoiceItem(1, 'Культурная')
    sports = djchoices.ChoiceItem(2, 'Спортивная')
    social = djchoices.ChoiceItem(4, 'Общественная')


class EventLevelChoices(djchoices.DjangoChoices):
    international = djchoices.ChoiceItem(0, 'Международный')
    all_russian = djchoices.ChoiceItem(1, 'Всероссийский')
    regional = djchoices.ChoiceItem(2, 'Региональный')
    urban = djchoices.ChoiceItem(3, 'Городской')
    university = djchoices.ChoiceItem(4, 'Университетский')


class Event(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название мероприятия')
    area = models.PositiveSmallIntegerField(choices=EventAreaChoices,
                                            verbose_name='Область мероприятия')
    level = models.PositiveSmallIntegerField(choices=EventLevelChoices,
                                             verbose_name='Уровень мероприятия')

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'

    def __str__(self):
        return self.name


class WinningPlaceChoices(djchoices.DjangoChoices):
    first = djchoices.ChoiceItem(1, '1 место')
    second = djchoices.ChoiceItem(2, '2 место')
    third = djchoices.ChoiceItem(3, '3 место')
    participation = djchoices.ChoiceItem(0, 'участие')


class EventGroup(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название')
    prize_winning_place = models.PositiveSmallIntegerField(choices=WinningPlaceChoices.choices,
                                                           verbose_name='Призовое место')
    students = models.ManyToManyField(Student, blank=True, verbose_name='Студенты')
    academic_group = models.ForeignKey(AcademicGroup, on_delete=models.CASCADE,
                                       verbose_name='Академическая группа')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name='Мероприятие')

    class Meta:
        verbose_name = 'Группа мероприятия'
        verbose_name_plural = 'Группы мероприятий'

    def __str__(self):
        return self.name

academic_groups/forms.py
from django import forms

from academic_groups.models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('name', 'academic_group', 'educational_form')

academic_groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from academic_groups.models import ExamResult, Student, AcademicGroup, EventGroup, AcademicGroupExam


class AcademicGroupDetailView(LoginRequiredMixin,
                              UserPassesTestMixin,
                              generic.DetailView):
    model = AcademicGroup

    def test_func(self):
        return self.request.user.groups.get().name == 'headman'


class StudentDetailView(LoginRequiredMixin,
                        generic.DetailView):
    model = Student


class StudentCreateView(LoginRequiredMixin,
                        generic.CreateView):
    model = Student
    fields = ('name', 'academic_group', 'educational_form')
    success_url = reverse_lazy('home')

    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)
        for exam in self.object.academic_group.academicgroupexam_set.all():
            self.object.examresult_set.create(academic_group_exam=exam)
        return response


class StudentDeleteView(LoginRequiredMixin,
                        generic.DeleteView):
    model = Student
    success_url = reverse_lazy('home')


class AcademicGroupExamListView(LoginRequiredMixin,
                                generic.ListView):
    def get_queryset(self):
        return AcademicGroup.objects.get(pk=self.request.user.academicgroup.pk).academicgroupexam_set.all()


class AcademicGroupExamCreateView(LoginRequiredMixin,
                                  generic.CreateView):
    model = AcademicGroupExam
    fields = ('exam',)
    success_url = reverse_lazy('groups:exam_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.academic_group = self.request.user.academicgroup
        self.object.save()
        for student in self.object.academic_group.student_set.all():
            ExamResult.objects.create(student=student, academic_group_exam=self.object)
        return super().form_valid(form)


class AcademicGroupExamDeleteView(LoginRequiredMixin,
                                  generic.DeleteView):
    model = AcademicGroupExam
    success_url = reverse_lazy('groups:exam_list')


def edit_student_exams(request, student_id):
    if request.POST:
        student = Student.objects.get(pk=student_id)

        student_exams = list(filter(lambda exam_result: exam_result.student == student, student.examresult_set.all()))

        for student_exam in student_exams:
            student_exam.score = request.POST['exam{0}'.format(student_exam.exam_id)]
            student_exam.save()

        return redirect(reverse("groups:student", args={
            student_id: student.id,
        }))
    else:
        return Http404()


def events(request):
    context = {
        'academic_group': request.user.academicgroup,
        'name': '{0} {1}'.format(request.user.first_name, request.user.last_name),
    }

    return render(request, 'academic_groups/events.html', context)


def add_event(request):
    if request.POST:
        event_group = EventGroup()
        event_group.name = request.POST['group_name']
        event_group.event_name = request.POST['event_name']
        event_group.event_area = request.POST['event_area']
        event_group.event_level = request.POST['event_level']
        event_group.prize_winning_place = request.POST['place']
        event_group.academic_group = request.user.academicgroup
        event_group.save()
        return redirect(reverse('groups:events'))


def event_add_student(request):
    if request.POST:
        event_group = EventGroup.objects.get(pk=request.POST['event_group_id'])
        student = Student.objects.get(pk=request.POST['student'])
        event_group.student_event.add(student)
        event_group.save()

        return redirect(reverse('groups:events'))


def edit_event_group(request):
    if request.POST:
        event_group = EventGroup.objects.get(pk=request.POST['event_id'])
        event_group.name = request.POST['group_name']
        event_group.event_name = request.POST['event_name']
        event_group.event_level = request.POST['event_level']
        event_group.prize_winning_place = request.POST['place']
        event_group.save()

        return redirect(reverse('groups:events'))


def delete_event_group(request):
    if request.POST:
        event_group = EventGroup.objects.get(pk=request.POST['event_group_id'])
        event_group.delete()

        return redirect(reverse('groups:events'))


def jury(request):
    context = {
        'academic_groups': AcademicGroup.objects.all(),
        'name': '{0} {1}'.format(request.user.first_name, request.user.last_name),
    }

    return render(request, 'academic_groups/jury.html', context)

academic_groups/templates/academic_groups/academicgroup_detail.html
{% extends 'base.html' %}

{% block header %}
  {% include 'academic_groups/header.html' %}
{% endblock %}

{% block content %}
  <div class="container mt-5">
    <h2>Результаты экзаменов</h2>
    <h4>Группа: {{ object.name }}</h4>

    <table class="table table-bordered table-hover">
      <thead class="thead-dark bg-primary">
      <tr class="bg-primary">
        <th rowspan="2" scope="col">Студент</th>
        <th colspan="{{ object.academicgroupexam_set.count }}" scope="col">Экзамены</th>
        <th rowspan="2" scope="col">Средний балл</th>
      </tr>
      <tr>
        {% for academic_group_exam in object.academicgroupexam_set.all %}
          <th>{{ academic_group_exam.exam.name }}</th>
        {% endfor %}
      </tr>
      </thead>
      <tbody>
      {% for student in object.student_set.all %}
        <tr>
          <td><a href="{% url 'groups:student_detail' student.pk %}">{{ student.name }}</a></td>
          {% for examresult in student.examresult_set.all %}
            <td>{{ examresult.score }}</td>
          {% endfor %}
          <td>{{ student.average_score }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    <div class="d-flex flex-column flex-md-row justify-content-end">
      <a class="btn btn-primary m-1" href="{% url 'groups:student_create' %}"
         role="button">Добавить студента</a>
      <a class="btn btn-primary m-1" href="{% url 'groups:exam_list' %}" role="button">Посмотреть экзамены</a>
      <a class="btn btn-primary m-1" href="#" role="button">Обновить результаты экзаменов</a>
    </div>
  </div>
{% endblock %}

academic_groups/templates/academic_groups/academicgroupexam_confirm_delete.html
{% extends 'base.html' %}

{% block header %}
  {% include 'academic_groups/header.html' %}
{% endblock %}

{% block content %}
  <div class="container mt-0 mt-md-5">
    <div class="row justify-content-center">
      <div class="col-12 col-md-5 p-2 p-md-4 shadow">
        <form method="post" class="d-flex flex-column">
          {% csrf_token %}
          <p class="text-center">Уверены, что хотите удалить экзамен <i><b>{{ object.name }}</b></i></p>
          <div class="d-flex flex-column flex-md-row">
            <button class="flex-fill btn btn-danger mx-0 mx-md-1 my-1 my-md-0">Удалить</button>
            <a href="{% url 'groups:exam_list' %}" class="flex-fill btn btn-primary mx-0 mx-md-1 my-1 my-md-0" role="button">Отмена</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

academic_groups/templates/academic_groups/academicgroupexam_list.html
{% extends 'base.html' %}

{% block header %}
  {% include 'academic_groups/header.html' %}
{% endblock %}

{% block content %}
  <div class="container mt-0 mt-md-5">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 shadow p-2 p-md-4">
        <h2 class="mb-4 text-center">Экзамены группы {{ object_list.first.academic_group.name }}</h2>
        <table class="table table-hover table-bordered">
          <thead class="thead-dark">
          <tr>
            <th>Экзамен</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          {% for academic_group_exam in object_list %}
            <tr>
              <td class="align-middle">{{ academic_group_exam.exam.name }}</td>
              <td class="text-center">
                <a href="{% url 'groups:exam_delete' academic_group_exam.pk %}" class="btn btn-danger btn-sm" role="button">
                  <i class="material-icons align-middle">delete</i>
                </a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>

        <div class="d-flex flex-column flex-md-row justify-content-end">
          <a href="{% url 'groups:exam_create' %}" class="btn btn-primary" role="button">Добавить экзамен</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

academic_groups/templates/academic_groups/events.html
{% extends 'academic_groups/header_events.html' %}

{% block content %}
<div class="container shadow " style="padding-top: 50px">
  <div class="panel-group" id="collapse-group">

    {% for event_group in academic_group.eventgroup_set.all %}

      <div class="panel panel-info">
        <a href="#el{{ event_group.id }}" data-toggle="collapse" data-parent="#collapse-group">
          <div class="panel-heading">
            <h3><b>Название группы:</b> {{ event_group }}</h3><br>
          </div>
        </a>

        <div class="collapse container" id="el{{ event_group.id }}">
          <div class="panel-body">
            <ul>
              <li><b>Место:</b>  {{ event_group.get_prize_winning_place_display }}</li>
              <li><b>Мероприятие:</b>  {{ event_group.event_name }}</li>
              <li><b>Область:</b>  {{ event_group.get_event_area_display }}</li>
              <li><b>Уровень:</b>  {{ event_group.get_event_level_display }}</li>
            </ul>

            <h4 style="margin-top: 30px; margin-bottom: 15px">Студенты-участники</h4>
            <ol>
              {% for student in event_group.student_event.all %}
                <li>{{ student.name }}</li>

              {% endfor %}
            </ol>
            <!-- BEGIN: add-student -->
            <button class="btn btn-default" data-toggle="modal" data-target="#add-student{{ event_group.id }}"><i class="fa fa-user-plus"></i> Добавить студента</button>

            <div id="add-student{{ event_group.id }}" class="modal fade" tabindex="-1">
                <div class="modal-dialog modal-sm">
                  <form class="modal-content" action="{% url 'groups:event_add_student' %}" method="post">
                    <div class="modal-header">
                      <button class="close" data-dismiss="modal">х</button>
                      <h4 class="modal-title">Добавить студента</h4>
                    </div>

                    <div class="modal-body">

                      {% csrf_token %}

                      <input type="hidden" name="event_group_id" value="{{ event_group.id }}">

                      <label for="student">ФИО</label>
                      <select id="student" name="student">
                        <option selected>Выберите</option>

                        {% for student in academic_group.student_set.all %}
                          {% if not student in event_group.student_event.all %}
                            <option value="{{ student.id }}">{{ student }}</option>
                          {% endif %}
                        {% endfor %}
                      </select>
                    </div>

                    <div class="modal-footer">
                      <input class="btn btn-default" type="submit" value="Добавить">
                      <!-- <a href="#"><button style="width: 100%" class="btn btn-default" type="button" name="button">Добавить</button></a> -->
                    </div>
                  </form>
                </div>
              </div>
              <!-- END: add-student -->

              <!-- BEGIN: delete_evebt -->
              <div style="float: right; margin-right: 15px">
                <form action="{% url 'groups:delete_event_group' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="event_group_id" value="{{ event_group.id }}">
                  <button class="btn btn-danger" type="submit" value="Удалить" name="button"><i class="fa fa-trash"></i> Удалить</button>
                </form>
              </div>
                <!-- END: delete_evebt -->

              <!-- BEGIN: edit-event -->
              <div style="float: right; margin-right: 10px">
                <button class=" btn btn-default" data-toggle="modal" data-target="#edit-event-group{{ event_group.id }}"><i class="glyphicon glyphicon-pencil" aria-hidden="true"></i> Редактировать</button>
                <div id="edit-event-group{{ event_group.id }}" class="modal fade" tabindex="-1">
                  <div class="modal-dialog modal-sm">
                    <form class="modal-content" action="{% url 'groups:edit_event_group' %}" method="post">
                      <div class="modal-header">
                        <button class="close" data-dismiss="modal">х</button>
                        <h3 class="modal-title">Редактировать мероприятие</h3>
                      </div>

                      <div class="modal-body">
                        {% csrf_token %}

                        <input type="hidden" name="event_id" value="{{ event_group.id }}">

                        <label for="group_name">Название группы:</label><br>
                        <input type="text" id="group_name" size="20" name="group_name" value="{{ event_group.name }}"><br>

                        <label for="event_name">Мероприятие:</label><br>
                        <input type="text" id="event_name" size="20" name="event_name" value="{{ event_group.event_name }}"><br>

                        <label for="event_area">Область:</label><br>
                        <select id="event_area" name="event_area">
                          <option selected value="{{ event_group.event_area }}">{{ event_group.get_event_area_display }}</option>
                          <option value="n">Научная</option>
                          <option value="k">Культурно-массовая</option>
                          <option value="s">Спортивная</option>
                          <option value="o">Общественная</option>
                        </select>

                        <br>
                        <label for="event_level">Уровень:</label><br>
                        <select id="event_level" name="event_level">
                          <option selected value="{{ event_group.event_level }}">{{ event_group.get_event_level_display }}</option>
                          <option value="m">Международный</option>
                          <option value="v">Всероссийский</option>
                          <option value="r">Региональный</option>
                          <option value="g">Городской</option>
                          <option value="u">Университетский</option>
                        </select>

                        <br>

                        <label for="place">Занятое место:</label><br>
                        <select id="place" name="place" >
                          <option selected value="{{ event_group.prize_winning_place }}">{{ event_group.get_prize_winning_place_display }}</option>
                          <option value="1">1 место</option>
                          <option value="2">2 место</option>
                          <option value="3">3 место</option>
                          <option value="0">участие</option>
                        </select>
                      </div>

                      <div class="modal-footer">
                        <input class="btn btn-default" type="submit" value="Сохранить">
                      </div>
                    </form>
                  </div>
                </div>
            </div> <!-- END: edit-event -->

          </div>
        </div>
      </div>

    {% endfor %}

    <!-- BEGIN: ADD_EVENT -->
    <div style="margin-top: 20px">
      <button style="float: right; width: 180px" class="btn btn-default" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Добавить мероприятие</button>
      <div id="myModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-md">
          <form class="modal-content" action="{% url 'groups:add_event' %}" method="post">
            <div class="modal-header">
              <button class="close" data-dismiss="modal">х</button>
              <h3 class="modal-title">Добавить мероприятие</h3>
            </div>

            <div class="modal-body">
              {% csrf_token %}

              <label for="group_name">Название группы:</label><br>
              <input type="text" id="group_name" size="20" name="group_name"><br>

              <label for="event_name">Мероприятие:</label><br>
              <input type="text" id="event_name" size="20" name="event_name"><br>

              <label for="event_area">Область:</label><br>
              <select id="event_area" name="event_area">
                <option selected>Выберите</option>
                <option value="n">Научная</option>
                <option value="k">Культурно-массовая</option>
                <option value="s">Спортивная</option>
                <option value="o">Общественная</option>
              </select>

              <br>
              <label for="event_level">Уровень:</label><br>
              <select id="event_level" name="event_level">
                <option selected>Выберите</option>
                <option value="m">Международный</option>
                <option value="v">Всероссийский</option>
                <option value="r">Региональный</option>
                <option value="g">Городской</option>
                <option value="u">Университетский</option>
              </select>

              <br>

              <label for="place">Занятое место:</label><br>
              <select id="place" name="place" >
                <option selected>Выберите занятое место</option>
                <option value="1">1 место</option>
                <option value="2">2 место</option>
                <option value="3">3 место</option>
                <option value="0">участие</option>
              </select>
            </div>

            <div class="modal-footer">
              <input class="btn btn-default" type="submit" value="Добавить">
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- END: ADD_EVENT -->
  </div>
</div>
{% endblock %}

academic_groups/templates/academic_groups/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
          aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Hidden brand</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:academicgroup_detail' request.user.academicgroup.pk %}">Студенты<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'groups:events' %}">Мероприятия</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Профиль
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Профиль</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'auth:logout' %}">Выйти</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

academic_groups/templates/academic_groups/jury.html
{% extends 'academic_groups/header_jury.html' %}


{% block content %}

  <div class="container shadow" style="padding-top: 50px">

    {% for academic_group in academic_groups %}

      <div class="panel-group" id="collapse-group">
        <div class="panel panel-info">
          <a href="#el{{ academic_group.id }}" data-toggle="collapse" data-parent="#collapse-group">
            <div class="panel-heading">
              <h3><b>Название группы:</b> {{ academic_group }}</h3><br>
            </div>
          </a>

          <div id="el{{ academic_group.id }}" class="collapse container event-block">
            <div class="panel-body event-block">
              <ul class="list-group">

                {% for event_group in academic_group.eventgroup_set.all %}

                  <li>
                    <a data-toggle="modal" data-target="#modal{{ event_group.id }}">{{ event_group.event_name }}</a>
                    <div id="modal{{ event_group.id }}" class="modal fade" tabindex="-1">
                      <div class="modal-dialog modal-md">
                        <form class="modal-content" action="" method="post">
                          <div class="modal-header">
                            <h2 class="modal-title"><b>{{ event_group.event_name }}</b></h2>
                          </div>

                          <div class="modal-body" style="margin-left: 110px">

                            <h3><b>Группа-участник: </b>{{ event_group }}</h3>
                            <h3><b>Область: </b>{{ event_group.get_event_area_display }}</h3>
                            <h3><b>Уровень: </b>{{ event_group.get_event_level_display }}</h3>
                            <h3><b>Место: </b>{{ event_group.get_prize_winning_place_display }}</h3>
                            <h3><b>Список студентов</b></h3>
                            <ul>

                              {% for student in event_group.student_event.all %}
                                <li>{{ student }}</li>
                              {% endfor %}

                            </ul>

                          </div>

                          <div class="modal-footer">
                            <a href="#"><button class="btn btn-danger" type="button" data-dismiss="modal" name="button">Закрыть</button></a>
                          </div>
                        </form>
                      </div>
                    </div>
                  </li>

                {% endfor %}

              </ul>
            </div>
          </div>
        </div>
      </div>

    {% endfor %}

  </div>

{% endblock %}

academic_groups/templates/academic_groups/jury_header.html
{% extends 'pages/../../../templates/base.html' %}

{% block header %}



  {% block content %}
  {% endblock %}

{% endblock %}

academic_groups/templates/academic_groups/student_confirm_delete.html
{% extends 'base.html' %}

{% block header %}
  {% include 'academic_groups/header.html' %}
{% endblock %}

{% block content %}
  <div class="container mt-2 mt-md-5">
    <div class="row justify-content-center align-items-center">
      <div class="col-12 col-md-5 shadow p-3 p-md-4">
        <form method="post" class="d-flex flex-column">
          {% csrf_token %}
          <p class="text-center">Уверены, что хотите удалить пользователя <i><b>{{ object.name }}</b></i></p>
          <div class="d-flex flex-column flex-md-row">
            <button class="flex-fill btn btn-danger mx-0 mx-md-1 my-1 my-md-0">Удалить</button>
            <a href="{% url 'groups:student_detail' object.pk %}" class="flex-fill btn btn-primary mx-0 mx-md-1 my-1 my-md-0" role="button">Отмена</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}