ProjectCBAG/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from ProjectCBAG import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('authorization.urls')),
    path('groups/', include('academic_groups.urls')),
]

authorization/urls.py
from django.urls import path

from authorization import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

authorization/models.py
from django.db import models

# Create your models here.

authorization/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label='Имя пользователя', max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', max_length=20,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))

authorization/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic

from authorization.forms import LoginForm


class LoginFormView(generic.View):
    form_class = LoginForm
    template = 'authorization/login.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect(reverse('home'))
        return render(request, self.template, {'form': form})


class LogoutView(generic.View):
    def get(self, request):
        logout(request)
        return redirect(reverse('home'))

authorization/templates/authorization/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh">
      <div class="col-12 col-md-5">
        <h2 class="text-center">Войти</h2>

        <form action="{% url 'auth:login' %}" method="post">

          {% csrf_token %}

          {% for field in form %}
            <div class="form-group">
              {{ field.label_tag }}
              {{ field }}
            </div>
          {% endfor %}

          <button class="btn btn-primary btn-block">Войти</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}